### ISSUE TITLE
`restrict` keyword error with cpp

### ISSUE THREAD

**Issue by bear24rw** [pambrozy/Base85#1]
I get the following errors when compiling as part of a cpp project. I believe the solution is to either remove the restrict qualifier from the header definitions, or conditionally define it out. (similar issue as here: https://github.com/Cyan4973/xxHash/issues/88)
```
base85/base85.h:47:32: error: expected ',' or '...' before 'dest'
 char* bintob85( char* restrict dest, void const* restrict src, size_t size );
                                ^~~~
base85/base85.h:54:32: error: expected ',' or '...' before 'dest'
 void* b85tobin( void* restrict dest, char const* restrict src );
```

**Comment by bear24rw** [comment]
My current workaround:
```
#define restrict
#include <base85.h>
```

**Comment by pambrozy** [comment]
Are you sure this issue concerns this Swift library? Based on the function names, I think you may have meant to create an issue on this repository instead: https://github.com/rafagafe/base85

**Comment by bear24rw** [comment]
You are correct!
